services:
  backend:
    build: .
    container_name: crypto-dashboard-backend
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  streamlit:
    build: .
    container_name: crypto-dashboard-streamlit
    command: streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: crypto-dashboard-db
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: cryptodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: crypto-dashboard-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
