apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-frontend
  labels:
    app: crypto-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-frontend
  template:
    metadata:
      labels:
        app: crypto-frontend
    spec:
      containers:
        - name: frontend
          image: aditya19joshi01/crypto-frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://crypto-backend:8000"
